import type { Patient, Conversation, DashboardStats, LabReport } from "./types"

export const mockPatients: Patient[] = [
  {
    id: "1",
    doctor_id: "doc1",
    name: "María García López",
    phone_number: "56912345678",
    drug_name: "Metformina",
    status: "in_progress",
    completed_at: null,
    created_at: "2026-04-15T10:30:00Z",
  },
  {
    id: "2",
    doctor_id: "doc1",
    name: "Juan Pérez Rodríguez",
    phone_number: "56923456789",
    drug_name: "Losartan",
    status: "completed",
    completed_at: "2026-05-01T14:20:00Z",
    created_at: "2026-03-20T08:15:00Z",
  },
  {
    id: "3",
    doctor_id: "doc1",
    name: "Ana Martínez Silva",
    phone_number: "56934567890",
    drug_name: "Omeprazol",
    status: "non_responsive",
    completed_at: null,
    created_at: "2026-04-01T16:45:00Z",
  },
  {
    id: "4",
    doctor_id: "doc2",
    name: "Carlos Sánchez Díaz",
    phone_number: "56945678901",
    drug_name: "Atorvastatina",
    status: "in_progress",
    completed_at: null,
    created_at: "2026-04-28T11:00:00Z",
  },
  {
    id: "5",
    doctor_id: "doc2",
    name: "Laura Torres Muñoz",
    phone_number: "56956789012",
    drug_name: "Metformina",
    status: "pending",
    completed_at: null,
    created_at: "2026-05-05T09:30:00Z",
  },
  {
    id: "6",
    doctor_id: "doc1",
    name: "Roberto Hernández Vega",
    phone_number: "56967890123",
    drug_name: "Losartan",
    status: "completed",
    completed_at: "2026-05-08T15:10:00Z",
    created_at: "2026-04-10T12:00:00Z",
  },
]

export const mockConversations: Conversation[] = [
  {
    id: "c1",
    patient_id: "1",
    direction: "inbound",
    message_type: "text",
    content: "Hola, tengo una consulta sobre mi medicamento",
    media_url: null,
    media_type: null,
    whatsapp_message_id: "wamid1",
    created_at: "2026-05-09T10:30:00Z",
  },
  {
    id: "c2",
    patient_id: "1",
    direction: "outbound",
    message_type: "text",
    content: "Hola María, ¿en qué puedo ayudarte?",
    media_url: null,
    media_type: null,
    whatsapp_message_id: "wamid2",
    created_at: "2026-05-09T10:31:00Z",
  },
  {
    id: "c3",
    patient_id: "2",
    direction: "inbound",
    message_type: "image",
    content: null,
    media_url: "https://example.com/selfie1.jpg",
    media_type: "image/jpeg",
    whatsapp_message_id: "wamid3",
    created_at: "2026-05-09T09:15:00Z",
  },
  {
    id: "c4",
    patient_id: "4",
    direction: "inbound",
    message_type: "audio",
    content: null,
    media_url: "https://example.com/audio1.ogg",
    media_type: "audio/ogg",
    whatsapp_message_id: "wamid4",
    created_at: "2026-05-09T08:45:00Z",
  },
  {
    id: "c5",
    patient_id: "3",
    direction: "outbound",
    message_type: "text",
    content: "Recordatorio: Por favor responda el cuestionario de seguimiento",
    media_url: null,
    media_type: null,
    whatsapp_message_id: "wamid5",
    created_at: "2026-05-08T14:00:00Z",
  },
]

export const mockStats: DashboardStats = {
  totalPatients: 6,
  completedPatients: 2,
  inProgressPatients: 2,
  nonResponsivePatients: 1,
  pendingPatients: 1,
  totalConversations: 45,
  mediaUploads: 12,
  completionRate: 33.3,
}

export const mockRetentionData = [
  { date: "Ene", active: 10, completed: 2 },
  { date: "Feb", active: 15, completed: 4 },
  { date: "Mar", active: 18, completed: 6 },
  { date: "Abr", active: 22, completed: 10 },
  { date: "May", active: 25, completed: 15 },
]

export const mockLabReports: LabReport[] = [
  {
    id: "lab1",
    drug_name: "Metformina",
    doctor_id: "doc1",
    generated_at: "2026-05-09T08:00:00Z",
    patient_count: 25,
    completed_count: 18,
    non_responsive_count: 3,
    report_json: { adherence_rate: 72, avg_completion_days: 45 },
  },
  {
    id: "lab2",
    drug_name: "Losartan",
    doctor_id: "doc1",
    generated_at: "2026-05-08T08:00:00Z",
    patient_count: 18,
    completed_count: 12,
    non_responsive_count: 2,
    report_json: { adherence_rate: 66.7, avg_completion_days: 52 },
  },
]

export const mockAISignals = [
  {
    id: "sig1",
    patient_id: "1",
    patient_name: "María García López",
    signal_type: "fatiga",
    confidence: 0.85,
    detected_at: "2026-05-09T10:00:00Z",
    description: "Posible fatiga detectada en análisis de voz",
  },
  {
    id: "sig2",
    patient_id: "4",
    patient_name: "Carlos Sánchez Díaz",
    signal_type: "adherencia_baja",
    confidence: 0.72,
    detected_at: "2026-05-08T15:30:00Z",
    description: "Patrón de respuestas indica posible baja adherencia",
  },
  {
    id: "sig3",
    patient_id: "2",
    patient_name: "Juan Pérez Rodríguez",
    signal_type: "mejoria",
    confidence: 0.91,
    detected_at: "2026-05-07T11:00:00Z",
    description: "Indicadores positivos de mejoría en seguimiento",
  },
]

export const mockMediaItems = [
  {
    id: "m1",
    patient_id: "1",
    patient_name: "María García López",
    type: "image" as const,
    url: "/placeholder-selfie.jpg",
    uploaded_at: "2026-05-09T10:30:00Z",
  },
  {
    id: "m2",
    patient_id: "2",
    patient_name: "Juan Pérez Rodríguez",
    type: "video" as const,
    url: "/placeholder-video.mp4",
    uploaded_at: "2026-05-08T14:20:00Z",
  },
  {
    id: "m3",
    patient_id: "4",
    patient_name: "Carlos Sánchez Díaz",
    type: "audio" as const,
    url: "/placeholder-audio.ogg",
    uploaded_at: "2026-05-07T09:15:00Z",
  },
]
